version: '3.8'

services:
  backpack-market-maker:
    build: .
    container_name: backpack-market-maker
    restart: unless-stopped
    environment:
      # 必需的环境变量 - API密钥
      - BACKPACK_KEY=${BACKPACK_KEY}
      - BACKPACK_SECRET=${BACKPACK_SECRET}
      
      # 可选环境变量
      - BACKPACK_PROXY_WEBSOCKET=${BACKPACK_PROXY_WEBSOCKET:-}
      - BASE_URL=${BASE_URL:-https://api.backpack.work}
      
      # 配置参数
      - CAPITAL=${CAPITAL:-100}
      - SYMBOL=${SYMBOL:-SOL_USDC_PERP}
      - EXCHANGE=${EXCHANGE:-backpack}
      - MARKET_TYPE=${MARKET_TYPE:-perp}
      
      # 数据库相关
      - ENABLE_DATABASE=${ENABLE_DATABASE:-false}
      
    volumes:
      # 挂载日志目录（可选）
      - ./logs:/app/logs
      
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # 可选：添加一个监控服务来查看日志
  monitor:
    image: alpine:latest
    container_name: backpack-monitor
    command: tail -f /dev/null
    volumes:
      - ./logs:/logs
    depends_on:
      - backpack-market-maker
    restart: unless-stopped
